language: generic
os: linux
dist: xenial

git:
  depth: 1

env:
  global:
    - BYOND_MAJOR="513"
    - BYOND_MINOR="1511"
    - TARGET_PROJECT_NAME="baystation12"
    - SPACEMAN_DMM_VERSION=suite-1.4

jobs:
  include:
    - name: "Run Linters - Dreamchecker"
      cache:
        directories:
          - $HOME/SpacemanDMM
      install:
        - chmod +x ./.travis/install_spaceman_dmm.sh
        - ./.travis/install_spaceman_dmm.sh dreamchecker
      script:
        - ~/dreamchecker

    - name: "Code Quality Check"
      addon:
        apt:
          packages:
            - python
            - python-pip
      env: 
        - TEST=CODE_QUALITY
      script:
        - bash ./.travis/run-test.sh
    
    - name: "Compile"
      addon: 
        apt:
          packages:
            - libc6-i386
            - libgcc1:i386
            - libstdc++6:i386
      cache:
        directories:
          - $HOME/BYOND-${BYOND_MAJOR}.${BYOND_MINOR}
      install:
        - chmod +x ./install-byond.sh
        - ./install-byond.sh
      script:
        - source $HOME/BYOND-${BYOND_MAJOR}.${BYOND_MINOR}/byond/bin/byondsetup
        - bash ./.travis/dm.sh ${TARGET_PROJECT_NAME}.dme

    - name: "Unit Test - Example Map"
      addon:
        apt:
          packages:
            - libc6-i386
            - libgcc1:i386
            - libstdc++6:i386
            - python
            - python-pip
      env: 
        - TEST=MAP MAP_PATH=example
      cache:
        directories:
          - $HOME/BYOND-${BYOND_MAJOR}.${BYOND_MINOR}
      install:
        - chmod +x ./install-byond.sh
        - ./install-byond.sh
      script:
        - bash ./.travis/run-test.sh

# TODO: Add more unit testing
