language: generic
os: linux
dist: bionic

git:
  depth: 5
# Build only the master-branch when building pushes to branches
branches:
  only:
    - master

env:
  global:
    - BYOND_MAJOR="513"
    - BYOND_MINOR="1536"
    - TARGET_PROJECT_NAME="baystation12"
    - RUST_G_VERSION="0.4.6"

before_install:
  - chmod +x ./scripts/install-byond.sh
  - find ./.travis -type f -print0 | xargs -0 chmod +x

jobs:
  include:
    - name: "Code Quality Check - SpacemanDMM"
      env:
        - SPACEMAN_DMM_VERSION=suite-1.6
      cache:
        directories:
          - $HOME/SpacemanDMM
      install:
        - ./.travis/install_spaceman_dmm.sh dreamchecker
      script:
        - ~/dreamchecker -c ./SpacemanDMM.toml

    - name: "Code Quality Check - run-test.sh"
      addon:
        apt:
          packages:
            - python
      env:
        - TEST=CODE_QUALITY
      script:
        - bash ./.travis/run-test.sh

#    - name: "Icon Validity Check"
#      env:
#        - TEST=ICON_VALIDITY
#      script:
#        - bash ./.travis/run-test.sh

    - name: "Compile"
      addon:
        apt:
          packages:
            - libc6-i386
            - libgcc1:i386
            - libstdc++6:i386
      cache:
        directories:
          - $HOME/BYOND-${BYOND_MAJOR}.${BYOND_MINOR}
      install:
        - ./scripts/install-byond.sh
      script:
        - source $HOME/BYOND-${BYOND_MAJOR}.${BYOND_MINOR}/byond/bin/byondsetup
        - bash ./.travis/dm.sh ${TARGET_PROJECT_NAME}.dme

    - name: "Unit Test - Example Map"
      addon:
        apt:
          packages:
            - libc6-i386
            - libgcc1:i386
            - libstdc++6:i386
      env:
        - TEST=MAP MAP_PATH=example
      cache:
        directories:
          - $HOME/BYOND-${BYOND_MAJOR}.${BYOND_MINOR}
      install:
        - ./scripts/install-byond.sh
        - ./.travis/install_rust_g.sh
      script:
        - source $HOME/BYOND-${BYOND_MAJOR}.${BYOND_MINOR}/byond/bin/byondsetup
        - bash ./.travis/run-test.sh

    - name: "Unit Test - Pluto Map"
      addon:
        apt:
          packages:
            - libc6-i386
            - libgcc1:i386
            - libstdc++6:i386
      env:
        - TEST=MAP MAP_PATH=tyclo-pluto
      cache:
        directories:
          - $HOME/BYOND-${BYOND_MAJOR}.${BYOND_MINOR}
      install:
        - ./scripts/install-byond.sh
        - ./.travis/install_rust_g.sh
      script:
        - source $HOME/BYOND-${BYOND_MAJOR}.${BYOND_MINOR}/byond/bin/byondsetup
        - bash ./.travis/run-test.sh

# TODO: Add more unit testing
