[culture_unathi]
language = "language_unathi_basic"
secondary_langs = ["language_spacer_basic"]
category = ["culture"]

[culture_unathi_old]
__extends = 'culture_unathi'
name = "Old Moghei"
description = """Before the apocalypse covered the surface of Moghes, \
	there used to be a myriad of colourful cultures and many other activities \
	such as theatricals, sports, and cooking. In present day and year, only \
	those remain as memories and old traditions still participated by people \
	who hasn’t given into the new tribalism risen from the ashes of Moghes. \
	There are only a small minority of them left on Moghes, but they thrive \
	elsewhere."""

[culture_unathi_new]
__extends = 'culture_unathi'
name = "Post-Moghei"
description = """The future is now. The past is past. As such has been \
	decided by the gods, the past is nothing more and should be forgotten. \
	Proto-tribalism rule the Moghes and believe in identities defined only by \
	eugenics, ferocity, and what colours their followers wear. Meanwhile less \
	inclined followers form new Post-Moghei identities from what they can scrap \
	together from what’s left of the old times on Moghes. A post-moghei are \
	either a warrior or simply resourceful person."""

[culture_unathi_nagnecan]
__extends = 'culture_unathi'
name = "Nagnecan"
description = """Following the colonization of Nagnec and the founding of the \
	Unathi Republic, it begun the formation of a new breed of culture based on the \
	Old Moghei and the less isolationist and non-tribal lineages of Post-Moghei. \
	Forming a more open-minded of an otherwise dated and insular homogenous culture. \
	Contact with other cultures draw few inspirations and new ideas that can be \
	observed in this relatively young Unathi culture."""
